# Generated by Django 5.2.4 on 2025-07-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('cover_letter', models.TextField()),
                ('profile_picture', models.ImageField(upload_to='profile_pics/')),
                ('cv', models.FileField(upload_to='cvs/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
